### ISSUE TITLE
matlab stand alone version link not available

### ISSUE THREAD

**Issue by smdb21** [fosterlab/PrInCE-Matlab#3]
Hi:
I just wanted to be sure to have the latest version but the link provided pointing to https://drive.google.com/open?id=1vFgY8Wi8SIr9zNliAJC666IelBbhmyIY is not available anymore. 
Could you update the link on the README?
thanks!

**Comment by GregStacey** [comment]
Yup, you're right! Thanks.

I'm compiling a new Windows standalone. I'll close this issue when that's uploaded and the link has been fixed.

**Comment by GregStacey** [comment]
The link was updated to the newest standalone version. Thanks again.
